### ISSUE TITLE
Improvement: Air vent difficult to print beautifully

### ISSUE THREAD

**Issue by dingyifei** [Smeltie/Hyperion#14]
The air vent with the shape of IIII is hard to print on most FDM machines because the frequent retraction and low volume&movement extrusion increases the chance of clogging. 

A way to make better air vents is to design them as wavy lines (small triangles) in and out of the case wall, from the top side it would look like 

```
<
 >
<
 >
```

So holes are open on Z instead of X/Y, making these lines printable as continuous lines

An example ![image](https://user-images.githubusercontent.com/15083013/189523066-15330938-7f96-471d-b069-1b38b2cedeb8.jpeg)

**Comment by Smeltie** [comment]
Thank you for the suggestion.
Hyperion is currently not a project that I’m actively working on.
And it appears most people seem to be able to print the little spokes just fine (since they are dialed in for a .4 nozzle specifically.
That’s not to say this is a bad idea or shouldn’t be added.
The project is open source and MIT licensed so feel free to add this as a forked version of sorts.
