### ISSUE TITLE
make an opening for the micro usb of the d1

### ISSUE THREAD

**Issue by CosmicSnow** [Smeltie/Hyperion#16]
it would be great to have a opening for the micro usb of the micro controller, 
it would let updates without the need to open lid

**Comment by Smeltie** [comment]
I purposely left this hole out because:
- the hole would need to be significantly bigger than the actual port because it’s recessed into the case.
- It would massively reduce structural integrity
- The main tray can be removed within a few seconds
- You only have to flash the trackers once by cable, after that you can reflash OTA (over the air) aka wirelessly afterwards.


So after considering all these things I decided it wasn’t worth the reduced strenght and massive hole at the front.
But I know several people have made edits of the case with said hole.
Hopefully this answered your suggestion/question.
